created 3 entity
DOCUTEE/Ergo pull request #36
Opened 2024-11-22 18:07 UTC by HiIamCuong

Đã tạo 3 entity Question,Conservation,Message

2024-11-23 04:01 UTC, DOCUTEE requested changes
Không push gì lên liên quan đến bin cả
thiếu viết DAO với services rồi Cường

2024-11-23 18:05 UTC, HiIamCuong commented
đã loại bỏ bin và thêm Dao và Service vào nha Quang

2024-11-24 07:19 UTC, DOCUTEE requested changes
OK

2024-11-24 07:20 UTC, DOCUTEE approved these changes
okkok

2024-11-24 07:20 UTC, merged